apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry-ui
spec:
  selector:
    matchLabels:
      app: schema-registry-ui 
  template:
    metadata:
      labels:
        app: schema-registry-ui
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: landoop/schema-registry-ui
        imagePullPolicy: Always
        name: schema-registry-ui
        ports:
        - containerPort: 8000
          name: ui
        env:
        # the url for the schema registry service
        - name: SCHEMAREGISTRY_URL
          value: "http://schema-registry-url:port"

---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry-ui
  labels:
    app: schema-registry-ui
spec:
  type: ClusterIP #visible only inside the K8S cluster
  selector:
    app: schema-registry-ui
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000